# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather
  pod 'RealmSwift'
  pod 'ObjectMapper', '~> 3.0'
  pod 'PKHUD', '~> 5.0'

  target 'WeatherTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ObjectMapper', '~> 3.0'
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
    end
end
